[package]
name = "sys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotly = "0.12.1"
serde = "1.0.219"
clap = { version = "4", features = ["derive"] }
sysinfo = "0.26"
